# -*- coding: utf-8 -*-
"""Stop and search.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LRCXm9WkWZ24GzqwsZfPSik23EucP4vt
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import pprint
import numpy as np

sns.set(color_codes=True)

# getting the url for data visualisation


def get_police_data():
    # request.get
    r = requests.get("https://data.police.uk/api/stops-street?poly=52.2,0.5:52.8,0.2:52.1,0.88&date=2020-06")
    pprint.pprint(r.json())

    # change data to json format
    data = r.json()

    # Use Pandas to create dataframe
    df = pd.DataFrame(data)

    # deleting columns that i don't need
    df.drop(["operation_name", "object_of_search"], axis=1, inplace=True)

    # Reassign issue Date.
    df["datetime"] = pd.to_datetime(df["datetime"])
    df.head()

    # separated ethnicity to one word 'black', 'white', 'mixed', and 'other'
    df['self_defined_ethnicity'] = df['self_defined_ethnicity'].str.replace('-', ' ')
    df['self_defined_ethnicity'] = df['self_defined_ethnicity'].str.replace('/', ' ')
    df['self_defined_ethnicity'] = df['self_defined_ethnicity'].str.replace(',', ' ')
    df['self_defined_ethnicity'] = df['self_defined_ethnicity'].str.split().str[0]

    # creating a new column called month
    df["month"] = df["datetime"].dt.month
    df.head()

    # # creates new columns for nested data in location
    df = df.join(df.pop('location').apply(pd.Series))

    df = df.join(df.pop('street').apply(pd.Series))

    # drop row where gender is 'Other'
    df = df.drop(df[df['gender'] == 'Other'].index)
    return df

