# -*- coding: utf-8 -*-
"""Covid19 data ica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y6TzOU5EZajj6915as43UXp3pbTL2WjS
"""

import pandas as pd


def get_covid_data():
    # load the data
    df = pd.read_csv("covid_19_module/Covid19.csv")

    df.dropna()
    df.dropna(axis="columns", how="all")
    df.dropna(axis="columns", how="any")

    # i changed the name of my data
    df_covid = df

    # slicing my dataframe
    df_slice = df_covid.loc[0:115027, "areaType":"newCasesBySpecimenDate-90+"]

    # i removed the columns that i didn't need.
    df_slice.drop(["newCasesBySpecimenDate-0_59", "newCasesBySpecimenDate-60+"], axis=1, inplace=True)

    # Reassigning date
    df_slice["date"] = pd.to_datetime(df_slice["date"])

    # Extracting the day column from date column
    df_slice["Day"] = df_slice["date"].dt.day_name()

    # Extracting the month column
    df_slice["Month"] = df_slice["date"].dt.month_name()

    # Creating a new column to show the total cases
    df_slice["Total_case"] = df_slice.apply(
        lambda x: x["newCasesBySpecimenDate-0_4"] + x["newCasesBySpecimenDate-10_14"] + x[
            "newCasesBySpecimenDate-15_19"] +
                  x["newCasesBySpecimenDate-20_24"] + x["newCasesBySpecimenDate-25_29"] + x[
                      "newCasesBySpecimenDate-55_59"] + x["newCasesBySpecimenDate-5_9"] + x[
                      "newCasesBySpecimenDate-60_64"] + x["newCasesBySpecimenDate-65_69"] + x[
                      "newCasesBySpecimenDate-70_74"] + x["newCasesBySpecimenDate-75_79"] + x[
                      "newCasesBySpecimenDate-80_84"] + x["newCasesBySpecimenDate-85_89"] + x[
                      "newCasesBySpecimenDate-90+"],
        axis=1)

    # to create a column showing the percentage cases
    df_slice["Percentage"] = (df_slice["Total_case"] / df_slice["Total_case"].sum()) * 100

    # drop rows for area names that are equal to United Kingdom
    df_slice = df_slice.drop(df_slice[df_slice['areaName'] == 'United Kingdom'].index)

    # returns the final data
    covid = df_slice
    return covid

